/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import logica.MovParavolico;

/**
 *
 * @author jesgu_000
 */
public class ExportForm extends javax.swing.JFrame {

    /**
     * Creates new form ExportForm
     */
    public ExportForm() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrmBasicos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spAngulo = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spDatos = new javax.swing.JSpinner();
        spVelViento = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spFin = new javax.swing.JSpinner();
        spInicio = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spVel = new javax.swing.JSpinner();
        bExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exportar Datos");

        pPrmBasicos.setBackground(new java.awt.Color(204, 204, 204));
        pPrmBasicos.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros Basicos"));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel1.setText("Angulo");

        spAngulo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spAnguloStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel2.setText("Velocidad Veinto");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel3.setText("Velocidad");

        spVelViento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spVelVientoStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel4.setText("Intervalo de Tiempo");

        spFin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spFinStateChanged(evt);
            }
        });

        spInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spInicioStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setText("Inicio");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setText("Fin");

        jLabel10.setText("grados");

        jLabel11.setText("m/s");

        jLabel12.setText("m/s");

        jLabel13.setText("s");

        jLabel14.setText("s");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel7.setText("Datos");

        spVel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spVelStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pPrmBasicosLayout = new javax.swing.GroupLayout(pPrmBasicos);
        pPrmBasicos.setLayout(pPrmBasicosLayout);
        pPrmBasicosLayout.setHorizontalGroup(
            pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrmBasicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPrmBasicosLayout.createSequentialGroup()
                        .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pPrmBasicosLayout.createSequentialGroup()
                                .addGap(103, 119, Short.MAX_VALUE)
                                .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(pPrmBasicosLayout.createSequentialGroup()
                                .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pPrmBasicosLayout.createSequentialGroup()
                                .addComponent(spVelViento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(pPrmBasicosLayout.createSequentialGroup()
                                .addComponent(spVel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(pPrmBasicosLayout.createSequentialGroup()
                                .addComponent(spAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(pPrmBasicosLayout.createSequentialGroup()
                                .addComponent(spInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addGroup(pPrmBasicosLayout.createSequentialGroup()
                                .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(spDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(spFin, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))))
                    .addGroup(pPrmBasicosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pPrmBasicosLayout.setVerticalGroup(
            pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrmBasicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(spVel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spVelViento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(11, 11, 11)
                .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pPrmBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bExportar.setText("Exportar");
        bExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pPrmBasicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pPrmBasicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void spAnguloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spAnguloStateChanged
        
    }//GEN-LAST:event_spAnguloStateChanged

    private void spVelVientoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spVelVientoStateChanged
        
    }//GEN-LAST:event_spVelVientoStateChanged

    private void spFinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spFinStateChanged
        
    }//GEN-LAST:event_spFinStateChanged

    private void spInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spInicioStateChanged
        
    }//GEN-LAST:event_spInicioStateChanged

    private void spVelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spVelStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spVelStateChanged

    private void bExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExportarActionPerformed
        JFileChooser jfc = new JFileChooser();        
        jfc.setDialogTitle("Guardar Salida ...");
        if(jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
            String path;
            if(!jfc.getSelectedFile().getName().endsWith(".csv")){
                path = jfc.getSelectedFile().getPath() + ".csv";
            }else{
                path = jfc.getSelectedFile().getPath();
            }
            
            Double angulo = (double)spAngulo.getValue();
            Double vel = (double)spVel.getValue();
            Double vel_viento = (double)spVelViento.getValue();
            Double inicio = (double)spInicio.getValue();
            Double fin = (double)spFin.getValue();
            Integer datos = (Integer)spDatos.getValue();
            if(datos > 0 && fin - inicio > 0){
                Double paso = (fin - inicio) / datos;
                MovParavolico mp = new MovParavolico(angulo * 2.0 * Math.PI / 360, vel, vel_viento);

                StringBuilder sb = new StringBuilder();
                sb.append("id,tiempo,x,y\n");
                for (int i = 0; i < datos; i++) {
                    mp.setTiempo(inicio + (i * paso));
                    sb.append(i+1).append(",").append(inicio + (i * paso)).append(",").append(mp.getPosX()).append(",").append(mp.getPosY()).append("\n");
                }

                try (java.io.PrintWriter print = new java.io.PrintWriter(new File(path))) {
                    print.write(sb.toString());
                    JOptionPane.showMessageDialog(this, "Archivo creado.", ":)", JOptionPane.INFORMATION_MESSAGE);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ExportForm.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "No se creo el archivo.", ":(", JOptionPane.ERROR_MESSAGE);
                } 
            }else{
                JOptionPane.showMessageDialog(this, "Se necesitan datos.", ":(", JOptionPane.ERROR_MESSAGE);
            }
             
        }
    }//GEN-LAST:event_bExportarActionPerformed

    private void myInit(){
        //Configuracion de spinners
        spAngulo.setModel(new SpinnerNumberModel(0.0, 0.0, 90.0, 0.1));
        spVel.setModel(new SpinnerNumberModel(0.0, 0.0, null, 0.1));
        spVelViento.setModel(new SpinnerNumberModel(0.0, null, null, 0.1));
        spInicio.setModel(new SpinnerNumberModel(0.0, 0.0, null, 0.1));
        spFin.setModel(new SpinnerNumberModel(0.0, 0.0, null, 0.1));
        spDatos.setModel(new SpinnerNumberModel(0, 0, null, 1));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pPrmBasicos;
    private javax.swing.JSpinner spAngulo;
    private javax.swing.JSpinner spDatos;
    private javax.swing.JSpinner spFin;
    private javax.swing.JSpinner spInicio;
    private javax.swing.JSpinner spVel;
    private javax.swing.JSpinner spVelViento;
    // End of variables declaration//GEN-END:variables
}
